// Generated by CoffeeScript 1.7.1
(function() {
  var Emberella, get, set;

  Emberella = window.Emberella;

  get = Ember.get;

  set = Ember.set;

  Emberella.FocusableMixin = Ember.Mixin.create({

    /*
      @property isFocusable
      @type Boolean
      @default true
      @final
     */
    isFocusable: true,
    attributeBindings: ['tabindex'],
    tabindex: 0,
    classNameBindings: ['hasFocus:focused'],
    hasFocus: false,
    focusIn: function(e) {
      if (e != null) {
        e.stopPropagation();
      }
      return set(this, 'hasFocus', true);
    },
    focusOut: function(e) {
      if (e != null) {
        e.stopPropagation();
      }
      return set(this, 'hasFocus', false);
    }
  });

}).call(this);
