// Generated by CoffeeScript 1.7.1

/*
@module emberella
@submodule emberella-mixins
 */

(function() {
  var Emberella, get, jQuery, typeOf,
    __slice = [].slice;

  Emberella = window.Emberella;

  jQuery = window.jQuery;

  get = Ember.get;

  typeOf = Ember.typeOf;


  /*
    Some views (like `Emberella.TagsInput`) are container views that contain a
    variety of child views and must share properties and collaborate in response
    to events. The `Emberella.MembershipMixin` allows child views to easily
    establish a stronger bond with a specified ancestor view.
  
    For example, each tag listing in `Emberella.TagsInput` inherits its template
    from its parent container. This allows tag items to be customized directly
    through the handlebars template or without subclassing the item view class.
    Additionally, each tag listing must communicate with the parent container in
    response to certain events --- easily accomplished using the `dispatch()`
    method.
  
    @class MembershipMixin
    @namespace Emberella
   */

  Emberella.MembershipMixin = Ember.Mixin.create({

    /*
      The path to the view this member view should collaborate with. Typically,
      the lead view will be an ancestor container view setup to manage multiple
      member views. (e.g. the tags input view or an autocomplete
      suggestions listing).
    
      @property leadViewBinding
      @type String
      @default 'parentView'
     */
    leadViewBinding: 'parentView',
    init: function() {
      this.applyInheritedBindings();
      return this._super();
    },

    /*
      Bind the array of properties specified in the `inherit` attribute and
      setup computed aliases to relavant properties on the lead view.
    
      For example, if `this.inherit` is `['template', 'isVisible:isChildVisible']`
      then this view's `template` property would become an alias for
      `leadView.template` and the `isVisible` property would become an alias for
      `leadView.isChildVisible`.
    
      @method applyInheritedBindings
      @chainable
     */
    applyInheritedBindings: function() {
      var inherit;
      inherit = this.inherit;
      if (!Ember.isArray(inherit)) {
        return this;
      }
      inherit.forEach((function(_this) {
        return function(binding) {
          var inheritComputed, path, property, propertyPath, _ref;
          _ref = binding.split(':'), property = _ref[0], path = _ref[1];
          path = path || property;
          propertyPath = 'leadView.' + path;
          inheritComputed = Ember.computed.alias(propertyPath);
          return Ember.defineProperty(_this, property, inheritComputed);
        };
      })(this));
      return this;
    },

    /*
      Attempt to call a method on the lead view.
    
      @method dispatch
      @param String message The method to call on the lead view
      @param Mixed arg/args... Arguments to send to the method on the lead view
      @chainable
     */
    dispatch: function() {
      var arg, args, leadView, message;
      message = arguments[0], arg = arguments[1], args = 3 <= arguments.length ? __slice.call(arguments, 2) : [];
      if (arg == null) {
        arg = this;
      }
      if (!(leadView = get(this, 'leadView')) || Ember.isEmpty(message) || get(leadView, 'disabled')) {
        return this;
      }
      args = [arg].concat(args);
      if (typeOf(leadView[message]) === 'function') {
        leadView[message].apply(leadView, args);
      }
      return this;
    }
  });

}).call(this);
