// Generated by CoffeeScript 1.7.1
(function() {
  var $, Emberella, jQuery;

  Emberella = window.Emberella;

  jQuery = window.jQuery;

  if (!$) {
    $ = jQuery;
  }

  Ember.ResizeHandler = Ember.Mixin.create({
    resizeEndDelay: 100,
    resizing: false,
    onResizeStart: Ember.K,
    onResizeEnd: Ember.K,
    onResize: Ember.K,
    debounceResizeEnd: Ember.computed(function() {
      return Emberella.debounce((function(_this) {
        return function(event) {
          if (_this.isDestroyed) {
            return;
          }
          _this.set('resizing', false);
          return typeof _this.onResizeEnd === "function" ? _this.onResizeEnd(event) : void 0;
        };
      })(this), this.get('resizeEndDelay'));
    }).property('resizeEndDelay'),
    resizeHandler: Ember.computed(function() {
      return jQuery.proxy(this.handleWindowResize, this);
    }).property(),
    handleWindowResize: function(event) {
      if (!this.get('resizing')) {
        this.set('resizing', true);
        if (typeof this.onResizeStart === "function") {
          this.onResizeStart(event);
        }
      }
      if (typeof this.onResize === "function") {
        this.onResize(event);
      }
      return this.get('debounceResizeEnd')(event);
    },
    didInsertElement: function() {
      this._super();
      return $(window).on('resize.' + Ember.guidFor(this), this.get("resizeHandler"));
    },
    willDestroy: function() {
      $(window).off('resize.' + Ember.guidFor(this), this.get("resizeHandler"));
      return this._super();
    }
  });

}).call(this);
