// Generated by CoffeeScript 1.7.1
(function() {
  Ember.ScrollHandlerMixin = Ember.Mixin.create({
    onScroll: Ember.K,
    didInsertElement: function() {
      this._super();
      return this.$().bind('scroll', (function(_this) {
        return function(event) {
          return Ember.run(_this, _this.onScroll, event);
        };
      })(this));
    },
    willDestroy: function() {
      var $element;
      $element = this.$();
      if ($element && $element.unbind) {
        $element.unbind('scroll');
      }
      return this._super();
    }
  });

}).call(this);
