// Generated by CoffeeScript 1.7.1
(function() {
  var Emberella, root, _ref;

  root = window;

  Emberella = root.Emberella = Ember.Namespace.create();

  Emberella.VERSION = '0.0.1';

  if ((_ref = Ember.libraries) != null) {
    _ref.register('Emberella', Emberella.VERSION);
  }

}).call(this);
