// Generated by CoffeeScript 1.7.1
(function() {
  Emberella.BaseViewMixin = Ember.Mixin.create({
    baseViewBinding: 'parentView.baseView',
    init: function() {
      this._super();
      return this.set('_self', this);
    }
  });

  Emberella.View = Ember.View.extend(Emberella.BaseViewMixin);

  Emberella.ContainerView = Ember.ContainerView.extend(Emberella.BaseViewMixin);

  Emberella.CollectionView = Ember.CollectionView.extend(Emberella.BaseViewMixin);

}).call(this);
